Travis CI: Disable built package deploying due to lack of compatibility
Yikes!  It seems that the built package can only be compatible with the same distro release the build envoronment has, or running `woeusbgui` will die with something like this:

```
Fatal Error: Mismatch between the program and library build versions detected.
The library used 2.8 (no debug,Unicode,compiler with C++ ABI 1009,wx containers,compatible with 2.6),
and your program used 2.8 (no debug,Unicode,compiler with C++ ABI 1002,wx containers,compatible with 2.6).
```

Don't bother build the product in GitHub Releases for now to avoid confusion.

Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>